# Generated by Django 4.1 on 2023-11-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('band_name', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('subgenre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price_clp', models.DecimalField(decimal_places=6, max_digits=10)),
                ('image', models.ImageField(upload_to='projects', verbose_name='Foto')),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
